@startuml
title Rencard Xpreess - Clases (simple)

class Vehicle {
  id
  model
  status
  dailyRate
}

class Customer {
  id
  fullName
  phone
}

class Reservation {
  id
  startDate
  endDate
  status
  total
}

class ReservationService {
  +createReservation()
  +changeStatus()
}

class AvailabilityEngine {
  +isAvailable()
}

interface INotifier {
  +sendSMS()
  +sendEmail()
}

ReservationService --> AvailabilityEngine
ReservationService --> INotifier

Reservation --> Vehicle
Reservation --> Customer

note right of ReservationService
Reutilizable interno:
Validadores / CRUD base
end note

@enduml
