@startuml
title Rencard Xpreess - Interfaces (simple)

interface IAuthProvider {
  +login()
  +verifyToken()
}

interface IPaymentGateway {
  +createPayment()
  +confirmPayment()
}

interface INotifier {
  +sendSMS()
  +sendEmail()
}

class FirebaseAuthAdapter
class StripeAdapter
class TwilioAdapter

FirebaseAuthAdapter ..|> IAuthProvider
StripeAdapter ..|> IPaymentGateway
TwilioAdapter ..|> INotifier

note right of FirebaseAuthAdapter
Reutilizable (COTS):
Firebase/Auth0
end note

note right of StripeAdapter
Reutilizable (COTS):
Stripe/PayPal
end note

note right of TwilioAdapter
Reutilizable (COTS):
Twilio/SendGrid
end note

@enduml
